#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Oct 03 14:38:03 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
